name: Upload AAR to Sonatype Nexus

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: "Upload AAR to Sonatype Nexus"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Set Build Variables
        id: vars
        run: |
          artifactId=$(sed -n -e 's/^POM_ARTIFACT_ID=//p' android/gradle.properties)-dev
          echo ::set-output name=artifactId::$artifactId
          version=$(sed -n -e 's/^VERSION_NAME=//p' android/gradle.properties).$GITHUB_RUN_NUMBER
          echo ::set-output name=version::$version
      - name: Upload
        env:
          SIGNING_KEY_ARMOR: ${{secrets.MAVEN_SIGNING_KEY_ARMOR_BASE64}}
          SIGNING_KEY_ID: ${{secrets.MAVEN_SIGNING_KEY_ID}}
          SIGNING_KEY_PASSWORD: ${{secrets.MAVEN_SIGNING_KEY_PASSPHRASE}}
          SONATYPE_NEXUS_USERNAME: ${{secrets.SONATYPE_NEXUS_USERNAME}}
          SONATYPE_NEXUS_PASSWORD: ${{secrets.SONATYPE_NEXUS_PASSWORD}}
        run: |
          echo "Replacing original version name with dev version name"
          sed -i "/^VERSION_NAME=/s/.*/VERSION_NAME=${{ steps.vars.outputs.version }}/" android/gradle.properties

          echo "Replacing original artifact ID with dev artifact ID"
          sed -i "/^POM_ARTIFACT_ID=/s/.*/POM_ARTIFACT_ID=${{ steps.vars.outputs.artifactId }}/" android/gradle.properties

          echo "Create .gpg key from secret"
          echo $SIGNING_KEY_ARMOR | base64 --decode > ./signingkey.asc
          gpg --quiet --output $GITHUB_WORKSPACE/signingkey.gpg --dearmor ./signingkey.asc

          cd android
          ./gradlew uploadArchives -Psigning.secretKeyRingFile=$GITHUB_WORKSPACE/signingkey.gpg -Psigning.password=$SIGNING_KEY_PASSWORD -Psigning.keyId=$SIGNING_KEY_ID
      - name: Close and release Sonatype repository
        if: ${{ success() }}
        env:
          SONATYPE_NEXUS_USERNAME: ${{secrets.SONATYPE_NEXUS_USERNAME}}
          SONATYPE_NEXUS_PASSWORD: ${{secrets.SONATYPE_NEXUS_PASSWORD}}
        run: |
          cd android
          ./gradlew closeAndReleaseRepository

          echo "### Maven Dependency" >> $GITHUB_STEP_SUMMARY
          echo "[Maven Central](https://search.maven.org/artifact/io.openmobilemaps/${{ steps.vars.outputs.artifactId }}/${{ steps.vars.outputs.version }}/aar)" >> $GITHUB_STEP_SUMMARY
          echo "| Git Commit | Artifact ID | Maven Version |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| $GITHUB_SHA | ${{ steps.vars.outputs.artifactId }} | ${{ steps.vars.outputs.version }} |" >> $GITHUB_STEP_SUMMARY
